config/routes.rb
TrustCrowd::Application.routes.draw do

  resources :problems do
    get :active,              :on => :member
    get :close,               :on => :member
    get :search,              :on => :collection
    get :participate,         :on => :member
    get :evaluate,            :on => :member
    get :evaluate_criteria,   :on => :member
    get :finish_evaluation,   :on => :member
    resources :trusts do
        post "/trust/:user_id" => 'trusts#trust', :on => :collection
        delete "/untrust/:user_id" => 'trusts#untrust', :on => :collection
        post "/delegate/:user_id" => 'trusts#delegate', :on => :collection
        post "/undelegate/:user_id" => 'trusts#undelegate', :on => :collection
    end
    resources :alternatives do
      get :pending,       :on => :collection
      get :rejected,      :on => :collection
      get :active,        :on => :member
      get :finish_voting, :on => :member
      get "vote/:decision" => "alternatives#vote", :on => :member
    end
    
    resources :criteria do
      get :pending,       :on => :collection
      get :rejected,      :on => :collection
      get :active,        :on => :member
      get :finish_voting, :on => :member
      get "vote/:decision" => "criteria#vote", :on => :member
      
      resources :evaluations do
        get :get, :on => :collection
        post :save, :on => :collection
      end
      
      resources :criteria_evaluations do
        get :get, :on => :collection
        post :save, :on => :collection
      end
      
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  authenticated :user do
    root :to => 'users#index'
  end
  
  get "/indv" => 'decisions#getIndividual'
  get "/coll" => 'decisions#getCollectiveDecision'
  get '/u_sat' =>  'decisions#user_satisfactory'
  get '/g_sat' =>  'decisions#group_satisfactory'
  
  get "/" => 'home#index'
  
end

app/models/problem.rb
class Problem < ActiveRecord::Base
  
  serialize :criteria_matrix
  
  has_many  :users_problems
  has_many  :users, :through => :users_problems
  has_many  :alternatives
  has_many  :criteria
  has_many  :tweets
  has_many  :trusts
  
  validates :name, uniqueness: true
  validates :name, :desc, presence: true
  
  PENDING = "pending"
  ACTIVE  = "active"
  CLOSED  = "closed"
  STATUS  = [PENDING, ACTIVE, CLOSED]
  
  scope :active, where(:status => ACTIVE)
  
  def activate
    self.status = ACTIVE
    self.save
  end
  
  def close
    self.status = CLOSED
    self.save
  end
  
  def pending?
    self.status == PENDING
  end
  
  def active?
    self.status == ACTIVE
  end
  
  def subcriteriaOf(parent_id)
    self.criteria.where(:reject => false, :parent_id => parent_id)
  end
  
  def parentCriteria
    self.criteria.select(&:hasSubcriteriaToEvaluate?).map{|c| [c.name, c.id] }
  end
  
  def getParentSubCriteriaForEvaluation
    criteria = {}
    self.criteria.select(&:active?).each do |criterium|
      criteria.include?(criterium.parent_id) ? criteria[criterium.parent_id].append([criterium.name, criterium.id]) : (criteria[criterium.parent_id] = [[criterium.name, criterium.id]])
    end
    puts criteria
    buildTree(criteria)
  end
  
  def getParentSubCriteria
    criteria = {}
    self.criteria.where(:reject => false).each do |criterium|
      criteria.include?(criterium.parent_id) ? criteria[criterium.parent_id].append([criterium.name, criterium.id]) : (criteria[criterium.parent_id] = [[criterium.name, criterium.id]])
    end
    tree = buildTree(criteria);
    [["No. Parent", -1]].concat(tree || [])
  end
  
  def buildTree(src)
    res = src.delete(-1)
    depth = 1
    while src.count > 0
      str = "--"*depth
      tmp = []
      res.each do |c|
        if src.include?(c[1])
          tmp.concat( [c].concat(src[c[1]].map{|s| ["#{str}| #{s[0]}", s[1]] }) )
          src.delete(c[1])
        else
          tmp.append(c)
        end
      end
      res = tmp.clone
      depth += 1
    end
    res
  end
  
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem, only: [:show, :edit, :update, :destroy, :active, :close, :participate, :evaluate, :evaluate_criteria, :finish_evaluation, :ranking]
  # GET /problems
  # GET /problems.json
  def index
    problem_status = params["status"]
    @problems = []
    if Problem::STATUS.include?(problem_status)
      @problems = current_user.problems.where(:status => problem_status)
      @status = problem_status
    end
    respond_to do |format|
      format.js
    end
  end
  
  def search
    @q = params[:q] || ""
    search_for = "%#{@q}%"
    @problems = Problem.where("name like ? or desc like ? or tw_hash like ? ", search_for, search_for, search_for).paginate(:page => params[:page])
  end
  
  # GET /problems/1
  # GET /problems/1.json
  def show
    render layout: false
  end

  # GET /problems/new
  def new
    @problem = Problem.new
    render layout: false
  end

  # GET /problems/1/edit
  def edit
    render layout: false
  end

  # POST /problems
  # POST /problems.json
  def create
    @problem = Problem.new(problem_params)
    @problem.tw_hash  = "tc_p#{Problem.count}"
    @problem.status   = Problem::PENDING
    if @problem.save
      UsersProblem.create(:user => current_user, :problem => @problem, :owner => true)
      render text: @problem.id, layout: false
    else
      render template: "problems/new.html.erb", layout: false
    end
  end

  # PATCH/PUT /problems/1
  # PATCH/PUT /problems/1.json
  def update
    if @problem.update(problem_params)
      render text: @problem.id, layout: false
    else
      render template: "problems/edit.html.erb", layout: false
    end
  end

  # DELETE /problems/1
  # DELETE /problems/1.json
  def destroy
    redirect_to root_path
  end

  # GET /problems/1/active
  def active
    Problem.transaction do
      if @problem.activate
        if @problem.criteria.first.weight.nil? or @problem.criteria.first.weight.empty?
          @problem.criteria.update_all(:weight => (1/Float(@problem.criteria.count)))
        end
        render text: @problem.id, layout: false
      end
    end
  end
  
  # GET /problems/1/active
  def close
    if @problem.close
      render text: @problem.id, layout: false
    end
  end

  # GET /problems/1/participate
  def participate
    if @problem and !@problem.users.exists?(current_user)
      UsersProblem.create(:user => current_user, :problem => @problem, :owner => false)
      redirect_to root_path, :notice => "Successfully participated."
    end
  end
  
  def ranking
    criteria = @problem.criteria
    criteria_weights      = Matrix.rows([ criteria.map{|c| c.weight.to_f} ]).transpose
    criteria_evaluations  = Matrix.rows( criteria.map{|c| JSON.parse(c.alternatives_value)} ).transpose
    @alternative_weights  = criteria_evaluations * criteria_weights
    @alternatives         = @problem.alternatives
  end
  
  def evaluate
    @criteria = @problem.getParentSubCriteriaForEvaluation
    render layout: false
  end
  
  def evaluate_criteria
    @criteria = [["All Criteria", -1]].concat(@problem.parentCriteria)
    render layout: false
  end
  
  def finish_evaluation
    # TODO: calculate the aggregated decision
    # TODO: send the collective decision for the group e.g. {"alt_1": 0.3, "alt_2": 0.7}
    render text: @problem.id, layout: false
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def problem_params
      params.require(:problem).permit(:name, :desc)
    end
    
end

app/helpers/problems_helper.rb
module ProblemsHelper
end

app/views/problems/_form.html.erb
<%= form_for @problem, :remote => true, html: {class: "form-horizontal pull-left problem-form"} do |f| %>
	<% if @problem.errors.any? %>
		<div id="error_explanation">
			<h4><%= pluralize(@problem.errors.count, "error") %> prohibited this problem from being saved:</h4>
			<ul>
				<% @problem.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="control-group">
		<%= f.label :name, class: "control-label", for: "problem_name"%>
		<div class="controls">
			<%= f.text_field :name, class: "input-xlarge", required: "required" %>
		</div>
	</div>
 	
 	<div class="control-group">
		<%= f.label "Description", class: "control-label", for: "problem_desc" %>
		<div class="controls">
			<%= f.text_area :desc, class: "input-xxlarge", required: "required", row: 10 %>
		</div>
	</div>
	<div class="control-group">
		<div class="actions controls">
	    	<%= f.submit @problem.new_record? ? "Create Problem" : "Update Problem", :id => "create_problem", :class => "btn btn-primary" %>
		</div>
	</div>
<% end %>

app/views/problems/_list_problems.html.erb
<li class="nav-header"> <h5> <%= @status.camelize %> Problems <h5> </li>
<% unless @problems.empty? %>
	<% @problems.each do |p| %>
		<li>
			<%= link_to p.name, problem_path(p), :remote => true, :class => "prob", :id => p.id %>
		</li>	
	<% end %>
<% else %>
	<h6> No <%= @status.camelize %> problems.</h6>
<% end %>

app/views/problems/edit.html.erb
<h3>Editing problem</h3>

<%= render 'form' %>

app/views/problems/evaluate.html.erb
<div id="group_decision_chart"> </div>
<div id="user_decision_chart"> </div>

<div id="evaluation_criteria">
	<label class="control-label"> Select Criteria To evaluate: </label>
	<select id="criteria_list" class="input-large">
		<% selected = "" %>
		<% @criteria.each do |criteria| %>
			<option value="<%= criteria[1] %>" <%= criteria[0] == @selected ? "SELECTED" : "" %> > <%= criteria[0] %> </option>
		<% end %>
	</select>
</div>

<div id="alt_comparison" align="center">
	<div id="evaluation_div">
		
	</div>
</div>

<div class="float-left">
	<%= link_to 'Finish Evaluate', finish_evaluation_problem_path(@problem), :class => "btn btn-primary problem-finish-evaluate", :remote => true %>
</div>

<script type="text/javascript">
	$(function(){
		var prob_id = <%= @problem.id %>
		window.tc.getIndvDecision("user_decision_chart", prob_id);
		window.tc.getGroupDecision("group_decision_chart", prob_id);
		get_criteria_evaluation_matrix();
	});
	
	function get_criteria_evaluation_matrix(){
		var prob_id = <%= @problem.id %>
		url = "/problems/" + prob_id + "/criteria/" + $("#criteria_list option:selected").val() + "/evaluations/get"
		$.ajax({
			      type: "GET",
			      url: url,
			      dataType: "script",
			      success: function(){
			        init_sliders();
		          }
			  });
	}
	
	function init_sliders() {
		$.each($(".sliders"), function(i, val){
			slider = $("#"+val.id)
			v = parseFloat(slider.data()["val"]);
			$( "#"+this.id+"-val" ).data("actual_value", v);
			if(v < 1){
				v = (1 / v)
				v -= 1;
			}else{
				v *= -1;
				v += 1;
			}
			slider.slider({
				min: -8,
				max: 8,
				step: 2,
				value: v,
				slide: function( event, ui ) {
					value = ui.value
					if (value > 0){
						actual_value = 1 / (value+1) 
						$( "#"+this.id+"-val" ).data("actual_value", actual_value);
					}else if(value < 0 ){
						value *= -1;
						$( "#"+this.id+"-val" ).data("actual_value", value+1);
					}else if(value == 0){
						$( "#"+this.id+"-val" ).data("actual_value", value+1);
					}
					value += 1;
					$( "#"+this.id+"-val" ).html( parseInt(value) );
				}
			});
		});
	};
	
	$("#criteria_list").change(function() {
		get_criteria_evaluation_matrix();
	});
	
	function saveEvaluation(){
		var values = {}
		var prob_id = <%= @problem.id %>;
		$(".sliders-vals").each(function(i) {
			values[this.id] =  $("#"+this.id).data()["actual_value"];
		});
		url = "/problems/" + prob_id + "/criteria/" + $("#criteria_list option:selected").val() + "/evaluations/save"
		$.ajax({
			      type: "POST",
			      url: url,
			      data: {'matrix': values},
			      success: function(resp){
			      	get_criteria_evaluation_matrix();
			      	alert(resp);
			      	window.tc.getIndvDecision("user_decision_chart", prob_id);
			      }
			  });
	}
</script>

app/views/problems/evaluate_criteria.html.erb
<div id="evaluation_criteria">
	<label class="control-label"> Select Criteria To evaluate: </label>
	<select id="criteria_list" class="input-large">
		<% selected = "" %>
		<% @criteria.each do |criteria| %>
			<option value="<%= criteria[1] %>" <%= criteria[0] == @selected ? "SELECTED" : "" %> > <%= criteria[0] %> </option>
		<% end %>
	</select>
</div>

<div id="alt_comparison" align="center">
	<div id="evaluation_div">
		
	</div>
</div>

<div class="float-left">
	<%= link_to 'Finish Evaluate', finish_evaluation_problem_path(@problem), :class => "btn btn-primary problem-finish-evaluate", :remote => true %>
</div>

<script type="text/javascript">
	$(function(){
		get_criteria_evaluation_matrix();
	});
	
	function get_criteria_evaluation_matrix(){
		url = "/problems/" + <%= @problem.id %> + "/criteria/" + $("#criteria_list option:selected").val() + "/criteria_evaluations/get"
		$.ajax({
			      type: "GET",
			      url: url,
			      dataType: "script",
			      success: function(){
			        init_sliders();
		          }
			  });
	}
	
	function init_sliders() {
		$.each($(".sliders"), function(i, val){
			slider = $("#"+val.id)
			v = parseFloat(slider.data()["val"]);
			$( "#"+this.id+"-val" ).data("actual_value", v);
			if(v < 1){
				v = (1 / v)
				v -= 1;
			}else{
				v *= -1;
				v += 1;
			}
			slider.slider({
				min: -8,
				max: 8,
				step: 2,
				value: v,
				slide: function( event, ui ) {
					value = ui.value
					if (value > 0){
						actual_value = 1 / (value+1) 
						$( "#"+this.id+"-val" ).data("actual_value", actual_value);
					}else if(value < 0 ){
						value *= -1;
						$( "#"+this.id+"-val" ).data("actual_value", value+1);
					}else if(value == 0){
						$( "#"+this.id+"-val" ).data("actual_value", value+1);
					}
					value += 1;
					$( "#"+this.id+"-val" ).html( parseInt(value) );
				}
			});
		});
	};
	
	$("#criteria_list").change(function() {
		get_criteria_evaluation_matrix();
	});
	
	function saveEvaluation(){
		values = {}
		$(".sliders-vals").each(function(i) {
			values[this.id] =  $("#"+this.id).data()["actual_value"];
		});
		url = "/problems/" + <%= @problem.id %> + "/criteria/" + $("#criteria_list option:selected").val() + "/criteria_evaluations/save"
		$.ajax({
			      type: "POST",
			      url: url,
			      data: {'matrix': values},
			      success: function(resp){
			      	get_criteria_evaluation_matrix();
			      	alert(resp);
			      }
			  });
	}
</script>

app/views/problems/index.html.erb
<h1>Listing problems</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th>Tw hash</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @problems.each do |problem| %>
      <tr>
        <td><%= problem.name %></td>
        <td><%= problem.desc %></td>
        <td><%= problem.tw_hash %></td>
        <td><%= link_to 'Show', problem %></td>
        <td><%= link_to 'Edit', edit_problem_path(problem) %></td>
        <td><%= link_to 'Destroy', problem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Problem', new_problem_path %>

app/views/problems/index.js.erb
$("#<%= @status %>_problems").html("<%= escape_javascript(render 'list_problems') %>");

app/views/problems/new.html.erb
<h3>Create New problem</h3>

<%= render 'form' %>

app/views/problems/search.html.erb
<% if @q.empty? || @q.nil? %>
	<h3>All Problems </h3>
<% else %>
	<h3>Search result for '<%= @q %>' </h3>
<% end %>

<% if @problems.count > 0 %>
	
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Desc</th>
	      <th>Tw hash</th>
	      <th></th>
	    </tr>
	  </thead>
	
	  <tbody>
	    <% @problems.each do |problem| %>
	      <tr>
	        <td><%= problem.name %></td>
	        <td><%= problem.desc %></td>
	        <td><%= problem.tw_hash %></td>
	        <% if !problem.users.exists?(current_user) %>
	        	<td style="text-align: center !important"><%= link_to 'Participate', participate_problem_path(problem), data: { confirm: 'Are you sure?' } %></td>
        	<% else %>
        		<td style="text-align: center !important"> * </td>
	        <% end %>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	
	<h6>* Means that you already participated in this problem.</h6>
	
	<%= will_paginate @problems, :class => "pagination" %>
	
<% else %>
	<% if @q.empty? || @q.nil? %>
		<h4> There is no problems yet.</h4>
	<% else %>
		<h3> There is no problems matched your search words.</h3>
	<% end %>
<% end %>

<%= link_to 'Show All Problems', search_problems_path, class: "btn btn-primary" %>

app/views/problems/show.html.erb
<p id="notice"><%= notice %></p>

<p> <strong><%= @problem.name %>: </strong> #<%= @problem.tw_hash %> </p>

<dl>
	<dt> Description. </dt>
	<dd><%= @problem.desc %></dd>
</dl>


<% if @problem.pending? %>
	<%= link_to 'Edit', edit_problem_path(@problem), :class => "btn btn-primary problem-edit", :remote => true %>
	<%= link_to 'Activate the problem', active_problem_path(@problem), :class => "btn btn-primary problem-activate", :remote => true, data: { confirm: 'Are you sure?' } %>
<% end %>


<% if @problem.active? %>
	<%= link_to 'Evaluate Criteria', evaluate_criteria_problem_path(@problem), :class => "btn btn-primary problem-evaluate-criteria", :remote => true %>
	<%= link_to 'Evaluate Alternatives', evaluate_problem_path(@problem), :class => "btn btn-primary problem-evaluate", :remote => true %>
	<%= link_to "Trusts", problem_trusts_path(@problem), :class => "btn btn-primary" %>
	<br />
	<br />
	<%= link_to 'Close the problem', close_problem_path(@problem), :class => "btn btn-primary problem-close", :remote => true, data: { confirm: 'Are you sure?' } %>
<% end %>