config/routes.rb
TrustCrowd::Application.routes.draw do

  resources :problems do
    get :active,              :on => :member
    get :close,               :on => :member
    get :search,              :on => :collection
    get :participate,         :on => :member
    get :evaluate,            :on => :member
    get :evaluate_criteria,   :on => :member
    get :finish_evaluation,   :on => :member
    resources :trusts do
        post "/trust/:user_id" => 'trusts#trust', :on => :collection
        delete "/untrust/:user_id" => 'trusts#untrust', :on => :collection
        post "/delegate/:user_id" => 'trusts#delegate', :on => :collection
        post "/undelegate/:user_id" => 'trusts#undelegate', :on => :collection
    end
    resources :alternatives do
      get :pending,       :on => :collection
      get :rejected,      :on => :collection
      get :active,        :on => :member
      get :finish_voting, :on => :member
      get "vote/:decision" => "alternatives#vote", :on => :member
    end
    
    resources :criteria do
      get :pending,       :on => :collection
      get :rejected,      :on => :collection
      get :active,        :on => :member
      get :finish_voting, :on => :member
      get "vote/:decision" => "criteria#vote", :on => :member
      
      resources :evaluations do
        get :get, :on => :collection
        post :save, :on => :collection
      end
      
      resources :criteria_evaluations do
        get :get, :on => :collection
        post :save, :on => :collection
      end
      
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  
  authenticated :user do
    root :to => 'users#index'
  end
  
  get "/indv" => 'decisions#getIndividual'
  get "/coll" => 'decisions#getCollectiveDecision'
  get '/u_sat' =>  'decisions#user_satisfactory'
  get '/g_sat' =>  'decisions#group_satisfactory'
  
  get "/" => 'home#index'
  
end

app/models/alternative.rb
class Alternative < ActiveRecord::Base
  belongs_to :problem
  has_many :pendingAlternativesEvaluations
  
  validates :name, uniqueness: true
  validates :name, :desc, presence: true
  
  scope :active, where(:reject => false)
  
  def acceptance_votes
    self.pendingAlternativesEvaluations.where(:decision => true).count
  end
  
  def refused_votes
    self.pendingAlternativesEvaluations.where(:decision => false).count
  end
  
end

app/controllers/alternatives_controller.rb
class AlternativesController < ApplicationController
  before_action :set_alternative, only: [:show, :edit, :update, :destroy, :active, :vote, :finish_voting]
  before_action :set_problem
  
  # GET /problems/:problem_id/alternatives
  def index
    @alternatives = @problem.alternatives.where(:pending => false, :reject => false).paginate(:page => params[:page])
    render layout: false
  end

  # GET /problems/:problem_id/alternatives/pending
  def pending
    @alternatives = @problem.alternatives.where(:pending => true).paginate(:page => params[:page])
    render layout: false
  end

  # GET /problems/:problem_id/alternatives
  def rejected
    @alternatives = @problem.alternatives.where(:pending => false, :reject => true).paginate(:page => params[:page])
    render layout: false
  end
  
  # POST /problems/:problem_id/alternatives/:id/vote/:decision
  def vote
    decision = params[:decision] == "true"
    if @alternative.pendingAlternativesEvaluations.exists?(:user_id => current_user.id)
      @alternative.pendingAlternativesEvaluations.find_by(:user_id => current_user.id).update(:decision => decision)
      msg = "updated"
    else
      PendingAlternativesEvaluation.create(:problem_id => @problem.id, :alternative_id => @alternative.id, :user_id => current_user.id, :decision => decision)
      msg = "created"
    end
    render text: msg, layout: false
  end
  
  # GET /problems/:problem_id/alternatives/:id/finish_voting
  def finish_voting
    @alternative.pending = false
    if @alternative.acceptance_votes > @alternative.refused_votes
      @alternative.reject = false
      msg = "accepted"
    else
      @alternative.reject = true
      msg = "refused"
    end
    @alternative.save
    render text: msg, layout: false
  end

  # GET /problems/:problem_id/alternatives/1
  def show
    render layout: false
  end

  # GET /problems/:problem_id/alternatives/new
  def new
    @alternative = @problem.alternatives.new
    render layout: false
  end

  # GET /problems/:problem_id/alternatives/1/edit
  def edit
    render layout: false
  end

  # POST /problems/:problem_id/alternatives
  def create
    @alternative = @problem.alternatives.new(alternative_params)
    @alternative.tw_hash  = "#{@problem.tw_hash}_a#{@problem.alternatives.count}"
    if @problem.active?
      @alternative.pending = true
      @alternative.reject  = true
    else
      @alternative.pending = false
      @alternative.reject  = false
    end
    if @alternative.save
      render text: @alternative.id, layout: false
    else
      render template: "alternatives/new.html.erb", layout: false
    end
  end

  # PATCH/PUT /problems/:problem_id/alternatives/1
  def update
    if @alternative.update(alternative_params)
      render text: @alternative.id, layout: false
    else
      render template: "alternatives/edit.html.erb", layout: false
    end
  end

  # DELETE /problems/:problem_id/alternatives/1
  def destroy
    @alternative.reject = true
    @alternative.save
    render text: "ok", layout: false
  end

  # GET /problems/:problem_id/alternatives/1
  def active
    @alternative.reject = false
    @alternative.save
    render text: "ok", layout: false
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alternative
      @alternative = Alternative.find(params[:id])
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_problem
      @problem = Problem.find(params[:problem_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alternative_params
      params.require(:alternative).permit(:name, :desc, :problem_id)
    end
end

app/helpers/alternatives_helper.rb
module AlternativesHelper
end

app/views/alternatives/_form.html.erb
<%= form_for([@problem, @alternative], :remote => true, html: {class: "form-horizontal alt-form"}) do |f| %>
  <% if @alternative.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@alternative.errors.count, "error") %> prohibited this alternative from being saved:</h4>

      <ul>
      <% @alternative.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="control-group">
	    <%= f.label :name, :class => "control-label" %>
	    <div class="controls">
	    	<%= f.text_field :name, class: "input-xlarge", required: "required" %>
	    </div>
	</div>
	
	<div class="control-group">
		<%= f.label :desc, :class => "control-label" %>
		<div class="controls">
			<%= f.text_area :desc, class: "input-xxlarge", required: "required", row: 10 %>
		</div>
	</div>
  	<div class="control-group">
		<div class="controls">
    		<%= f.submit @alternative.new_record? ? "Create Alternative" : "Update Alternative", :id => "create_alternative", :class => "btn btn-primary" %>
  		</div>
	</div>
<% end %>

app/views/alternatives/edit.html.erb
<h3>Editing alternative</h3>

<%= render 'form' %>

app/views/alternatives/index.html.erb
<% if @alternatives.count > 0 %>
	<h3>Active alternatives</h3>
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Desc</th>
	      <th>Tw hash</th>
	      <th></th>
	      <th></th>
	      <th></th>
	    </tr>
	  </thead>
	
	  <tbody>
	    <% @alternatives.each do |alternative| %>
	      <tr>
	        <td><%= alternative.name %></td>
	        <td><%= alternative.desc %></td>
	        <td><%= alternative.tw_hash %></td>
	        <td><%= link_to "Details", problem_alternative_path(@problem, alternative), :class => "alt-details", :remote => true %></td>
	        <td><%= link_to "Edit", edit_problem_alternative_path(@problem, alternative), :class => "alt-edit", :remote => true %></td>
	        <td><%= link_to "Reject", problem_alternative_path(@problem, alternative), method: :delete, :class => "alt-reject", :remote => true %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	<%= will_paginate @alternatives, :class => "alt-active-pagination pagination" %>
<% else %>
	<div align="center">
		<h4> There is no active alternatives.</h4>
	</div>
<% end %>

app/views/alternatives/new.html.erb
<h3>Create new Alternative</h3>

<%= render 'form' %>

app/views/alternatives/pending.html.erb
<% if @alternatives.count > 0 %>
	<h3>Pending alternatives</h3>
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Desc</th>
	      <th>Tw hash</th>
	      <th># Acceptance</th>
	      <th># Refused</th>
	      <th></th>
	      <th></th>
	      <% if current_user.own?(@problem) %>
	      	<th></th>
	      <% end %>
	    </tr>
	  </thead>
	
	  <tbody>
	    <% @alternatives.each do |alternative| %>
	      <tr>
	        <td><%= alternative.name %></td>
	        <td><%= alternative.desc %></td>
	        <td><%= alternative.tw_hash %></td>
	        <td><%= alternative.acceptance_votes %></td>
	        <td><%= alternative.refused_votes %></td>
	        <td><%= link_to "Accept", "/problems/#{@problem.id}/alternatives/#{alternative.id}/vote/true", :class => "alt-accept-voting", :remote => true %></td>
	        <td><%= link_to "Refuse", "/problems/#{@problem.id}/alternatives/#{alternative.id}/vote/false", :class => "alt-refuse-voting", :remote => true %></td>
	        <% if current_user.own?(@problem) %>
	        	<td><%= link_to "Finish Voting", finish_voting_problem_alternative_path(@problem, alternative), :class => "alt-finish-voting", :remote => true %></td>
	        <% end %>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	<%= will_paginate @alternatives, :class => "alt-pending-pagination pagination" %>
<% else %>
	<div align="center">
		<h4> There is no pending alternatives.</h4>
	</div>
<% end %>

app/views/alternatives/rejected.html.erb
<% if @alternatives.count > 0 %>
	<h3>Rejected alternatives</h3>
	<table class="table table-hover">
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Desc</th>
	      <th>Tw hash</th>
	      <!-- <th></th> -->
	    </tr>
	  </thead>
	
	  <tbody>
	    <% @alternatives.each do |alternative| %>
	      <tr>
	        <td><%= alternative.name %></td>
	        <td><%= alternative.desc %></td>
	        <td><%= alternative.tw_hash %></td>
	        <!-- <td><%= link_to "Active", active_problem_alternative_path(@problem, alternative), :class => "alt-active", :remote => true %></td> -->
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	<%= will_paginate @alternatives, :class => "alt-rejected-pagination pagination" %>
<% else %>
	<div align="center">
		<h4> There is no rejected alternatives.</h4>
	</div>
<% end %>

app/views/alternatives/show.html.erb
<p id="notice"><%= notice %></p>

<p> <strong> <%= @alternative.name %>: </strong> #<%= @alternative.tw_hash %> </p>
<dl>
	<dt> Description. </dt>
	<dd><%= @alternative.desc %></dd>
</dl>